# 配置
SQLALCHEMY_DATABASE_URI = 'sqlite:///auth.db'
SQLALCHEMY_TRACK_MODIFICATIONS = False
SECRET_KEY = 'cckjksjoi1729jmkdl9203dkd'
DEFAULT_MODEL = "deepseek-r1:1.5b"
DEFAULT_TEMPERATURE = 0.5
DEFAULT_ENDPOINT = "http://localhost:11434/api/chat"

# 验证码配置
CAPTCHA_LENGTH = 4
CAPTCHA_WIDTH = 120
CAPTCHA_HEIGHT = 40
CAPTCHA_BACKGROUND = (255, 255, 255)
CAPTCHA_FONT_SIZE = 25
CAPTCHA_FONT_COLORS = [(0, 0, 0), (255, 0, 0), (0, 0, 255), (0, 128, 0)]
CAPTCHA_NOISE_POINTS = 50
CAPTCHA_NOISE_LINES = 3

# 邮件服务器配置
MAIL_SERVER = 'smtp.sina.cn'
MAIL_PORT = 465
MAIL_USE_SSL = True
MAIL_USERNAME = 'sun2moon@sina.cn'
MAIL_DEFAULT_SENDER = ('DeepSeek聊天室', 'hehe@sina.cn')
MAIL_PASSWORD = 'xxxxxx'  # 邮件服务器授权码
PASSWORD_RESET_SALT = 'deepskyblue'
PASSWORD_RESET_EXPIRE = 3600
